create table city
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table app_user
(
    id           bigint generated by default as identity,
    name         varchar(255),
    age          integer not null,
    gender       varchar(255),
    city_id      bigint,
    created_date date,
    primary key (id)
);

alter table app_user
    add constraint FK_app_user_city foreign key (city_id) references city;
